[2025-04-01T09:19:47.519+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:19:47.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:19:47.527+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:19:47.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:19:47.600+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:19:47.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:19:47.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:19:47.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.141 seconds
[2025-04-01T09:20:18.819+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:18.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:20:18.824+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:18.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:18.852+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:18.846+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:20:18.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:18.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.062 seconds
[2025-04-01T09:20:48.692+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:48.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:20:48.699+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:48.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:48.751+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:48.738+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:20:48.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:20:48.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.127 seconds
[2025-04-01T09:21:19.815+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:19.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:21:19.820+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:19.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:19.844+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:19.838+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:21:19.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:19.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.056 seconds
[2025-04-01T09:21:50.665+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:50.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:21:50.669+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:50.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:50.691+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:50.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:21:50.694+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:21:50.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.055 seconds
[2025-04-01T09:22:22.994+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:22.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:22:23.001+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:23.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:23.048+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:23.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:22:23.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:23.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.111 seconds
[2025-04-01T09:22:48.493+0000] {processor.py:161} INFO - Started process (PID=502) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:48.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:22:48.495+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:48.495+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:48.517+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:48.513+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:22:48.519+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:22:48.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.045 seconds
[2025-04-01T09:23:19.381+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:19.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:23:19.386+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:19.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:19.414+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:19.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:23:19.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:19.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.065 seconds
[2025-04-01T09:23:50.873+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:50.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:23:50.879+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:50.879+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:50.928+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:50.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:23:50.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:23:50.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.102 seconds
[2025-04-01T09:24:21.947+0000] {processor.py:161} INFO - Started process (PID=710) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:21.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:24:21.952+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:21.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:21.978+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:21.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:24:21.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:22.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.062 seconds
[2025-04-01T09:24:54.030+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:54.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:24:54.038+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:54.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:54.085+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:54.074+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:24:54.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:24:54.127+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.104 seconds
[2025-04-01T09:26:27.071+0000] {processor.py:161} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:27.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:26:27.081+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:27.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:27.146+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:27.131+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:26:27.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:27.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.154 seconds
[2025-04-01T09:26:58.757+0000] {processor.py:161} INFO - Started process (PID=153) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:58.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:26:58.761+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:58.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:58.788+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:58.782+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:26:58.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:26:58.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.061 seconds
[2025-04-01T09:27:30.337+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:27:30.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:27:30.348+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:27:30.347+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:27:30.440+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:27:30.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:27:30.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:27:30.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.213 seconds
[2025-04-01T09:28:01.891+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:01.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:28:01.895+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:01.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:01.923+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:01.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:28:01.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:01.949+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.061 seconds
[2025-04-01T09:28:32.564+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:32.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:28:32.567+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:32.566+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:32.589+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:32.585+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:28:32.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:28:32.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.067 seconds
[2025-04-01T09:29:04.342+0000] {processor.py:161} INFO - Started process (PID=425) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:04.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:29:04.354+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:04.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:04.432+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:04.418+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:29:04.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:04.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.200 seconds
[2025-04-01T09:29:35.810+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:35.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:29:35.815+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:35.814+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:35.846+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:35.840+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:29:35.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:29:35.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.071 seconds
[2025-04-01T09:30:04.053+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:04.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:30:04.058+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:04.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:04.082+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:04.077+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:30:04.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:04.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.060 seconds
[2025-04-01T09:30:35.564+0000] {processor.py:161} INFO - Started process (PID=635) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:35.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:30:35.569+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:35.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:35.644+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:35.635+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:30:35.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:30:35.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.120 seconds
[2025-04-01T09:31:04.876+0000] {processor.py:161} INFO - Started process (PID=711) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:04.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:31:04.882+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:04.882+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:04.929+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:04.919+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:31:04.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:04.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.104 seconds
[2025-04-01T09:31:35.785+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:35.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:31:35.791+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:35.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:35.834+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:35.825+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:31:35.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:31:35.898+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.118 seconds
[2025-04-01T09:32:03.856+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:03.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:32:03.863+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:03.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:03.903+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:03.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:32:03.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:03.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.099 seconds
[2025-04-01T09:32:34.543+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:34.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:32:34.550+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:34.549+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:34.589+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:34.583+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:32:34.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:32:34.627+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.092 seconds
[2025-04-01T09:33:04.778+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:04.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:04.783+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:04.783+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:04.814+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:04.809+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:04.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:04.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.067 seconds
[2025-04-01T09:33:35.783+0000] {processor.py:161} INFO - Started process (PID=1040) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:35.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:35.785+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:35.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:35.809+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:35.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:35.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:35.834+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.054 seconds
[2025-04-01T09:33:40.186+0000] {processor.py:161} INFO - Started process (PID=1045) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:40.194+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.294+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.278+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:40.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.165 seconds
[2025-04-01T09:33:40.469+0000] {processor.py:161} INFO - Started process (PID=1046) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:40.477+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.542+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:40.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.125 seconds
[2025-04-01T09:33:40.719+0000] {processor.py:161} INFO - Started process (PID=1047) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:40.728+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.804+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:40.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:40.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.156 seconds
[2025-04-01T09:33:41.128+0000] {processor.py:161} INFO - Started process (PID=1050) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:41.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:41.139+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:41.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:41.221+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:41.208+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:41.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:41.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.172 seconds
[2025-04-01T09:33:42.159+0000] {processor.py:161} INFO - Started process (PID=1056) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:42.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:42.165+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:42.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:42.210+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:42.203+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:42.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:42.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.100 seconds
[2025-04-01T09:33:44.378+0000] {processor.py:161} INFO - Started process (PID=1068) to work on /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:44.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_with_op_kwargs.py for tasks to queue
[2025-04-01T09:33:44.385+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:44.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:44.431+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:44.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_with_op_kwargs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_with_op_kwargs.py", line 5, in <module>
    from common.common_func import regist2
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:44.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_with_op_kwargs.py
[2025-04-01T09:33:44.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_with_op_kwargs.py took 0.108 seconds
