[2025-04-01T09:19:47.834+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:19:47.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:19:47.841+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:19:47.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:19:47.953+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:19:47.931+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:19:47.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:19:48.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.206 seconds
[2025-04-01T09:20:18.925+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:18.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:20:18.928+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:18.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:18.954+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:18.948+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:20:18.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:18.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.055 seconds
[2025-04-01T09:20:49.102+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:49.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:20:49.112+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:49.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:49.171+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:20:49.161+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:20:49.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:20:49.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.125 seconds
[2025-04-01T09:21:20.475+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:20.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:21:20.478+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:20.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:20.502+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:20.497+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:21:20.504+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:20.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.055 seconds
[2025-04-01T09:21:50.865+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:50.866+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:21:50.868+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:50.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:50.896+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:21:50.890+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:21:50.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:21:50.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.059 seconds
[2025-04-01T09:22:23.393+0000] {processor.py:161} INFO - Started process (PID=437) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:23.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:22:23.401+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:23.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:23.448+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:23.435+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:22:23.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:23.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.103 seconds
[2025-04-01T09:22:53.799+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:53.801+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:22:53.802+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:53.802+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:53.822+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:22:53.818+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:22:53.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:22:53.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.045 seconds
[2025-04-01T09:23:24.756+0000] {processor.py:161} INFO - Started process (PID=573) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:24.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:23:24.761+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:24.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:24.784+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:24.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:23:24.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:24.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.054 seconds
[2025-04-01T09:23:55.623+0000] {processor.py:161} INFO - Started process (PID=647) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:55.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:23:55.628+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:55.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:55.658+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:23:55.652+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:23:55.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:23:55.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.078 seconds
[2025-04-01T09:24:26.344+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:26.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:24:26.348+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:26.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:26.373+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:26.368+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:24:26.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:26.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.053 seconds
[2025-04-01T09:24:56.590+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:56.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:24:56.595+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:56.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:56.639+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:24:56.629+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:24:56.642+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:24:56.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.093 seconds
[2025-04-01T09:26:27.624+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:27.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:26:27.634+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:27.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:27.711+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:27.700+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:26:27.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:27.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.186 seconds
[2025-04-01T09:26:58.853+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:58.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:26:58.858+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:58.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:58.884+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:26:58.879+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:26:58.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:26:58.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.064 seconds
[2025-04-01T09:27:31.047+0000] {processor.py:161} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:27:31.053+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:27:31.063+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:27:31.062+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:27:31.149+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:27:31.136+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:27:31.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:27:31.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.247 seconds
[2025-04-01T09:28:02.171+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:02.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:28:02.175+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:02.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:02.207+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:02.201+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:28:02.211+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:02.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.071 seconds
[2025-04-01T09:28:32.744+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:32.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:28:32.748+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:32.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:32.773+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:28:32.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:28:32.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:28:32.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.048 seconds
[2025-04-01T09:29:04.956+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:04.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:29:04.969+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:04.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:05.106+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:05.093+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:29:05.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:05.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.250 seconds
[2025-04-01T09:29:33.921+0000] {processor.py:161} INFO - Started process (PID=509) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:33.923+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:29:33.927+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:33.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:33.959+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:29:33.953+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:29:33.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:29:33.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.074 seconds
[2025-04-01T09:30:04.945+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:04.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:30:04.949+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:04.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:04.974+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:04.970+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:30:04.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:04.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.050 seconds
[2025-04-01T09:30:36.181+0000] {processor.py:161} INFO - Started process (PID=640) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:36.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:30:36.188+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:36.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:36.266+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:30:36.252+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:30:36.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:30:39.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.146 seconds
[2025-04-01T09:31:05.215+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:05.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:31:05.221+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:05.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:05.270+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:05.259+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:31:05.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:05.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.109 seconds
[2025-04-01T09:31:36.384+0000] {processor.py:161} INFO - Started process (PID=772) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:36.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:31:36.394+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:36.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:36.449+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:31:36.440+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:31:36.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:31:36.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.124 seconds
[2025-04-01T09:32:07.308+0000] {processor.py:161} INFO - Started process (PID=845) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:07.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:32:07.312+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:07.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:07.345+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:07.338+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:32:07.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:07.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.078 seconds
[2025-04-01T09:32:38.215+0000] {processor.py:161} INFO - Started process (PID=913) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:38.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:32:38.218+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:38.218+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:38.247+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:32:38.242+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:32:38.250+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:32:38.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.059 seconds
[2025-04-01T09:33:10.449+0000] {processor.py:161} INFO - Started process (PID=980) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:10.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:33:10.454+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:10.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:10.487+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:10.479+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:10.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:10.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.070 seconds
[2025-04-01T09:33:40.960+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:40.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_python_import_func.py for tasks to queue
[2025-04-01T09:33:40.973+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:40.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:41.048+0000] {logging_mixin.py:188} INFO - [2025-04-01T09:33:41.033+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_python_import_func.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_python_import_func.py", line 5, in <module>
    from common.common_func import get_sftp # import 하는 경로 작성
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'common'
[2025-04-01T09:33:41.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_python_import_func.py
[2025-04-01T09:33:41.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_python_import_func.py took 0.146 seconds
